### PR TITLE
Add basic auth via requests library

### PR DESCRIPTION
**Pull request by etoulas**
Requests can do basic auth out of the box.

```python
requests.get('https://api.github.com/user', auth=('user', 'pass'))
```

This works also with POST requests.

Documentation: https://2.python-requests.org/en/master/user/authentication/#basic-authentication

### CODE REVIEW

**Comment by etoulas** [comment]
@vvaezian: This PR would benefit from some additional testing!

**Comment by vvaezian** [comment]
@etoulas  Thanks for the PR. I'll review it soon.

**Comment by vvaezian** [comment]
Is there a scenario where the current authentication cannot handle it and adding basic auth would make it possible?

**Comment by etoulas** [comment]
Glad you asked @vvaezian. My Metabase instance is behind a reverse proxy that asks for basic auth. It's accepts the same credentials as Metabase.

This is what happens
1. Make request to Metabase
2. Basic auth on reverse proxy
3. Login to Metabase instance
4. Access API

My initial approach gave more flexibilty by letting the user provide any basic auth credentials. But for my use case it was enough to use the same credentials for the requests library.

**Pull request merged**
